Change SQ to check for equal value
statistical-perceptions/participant-app pull request #17
Opened 2022-07-24 20:50 UTC by awqmayo

Instead of less than, as was previously implemented.

2022-08-01 20:08 UTC, brownsarahm requested changes
small change

2022-08-01 20:08 UTC, brownsarahm commented on src/items/sumQuestion.jsx
>                  alert("Your sum exceeds the maximum; please change the values inputted.")
change this to say the sum must equal the max value

2022-08-02 14:50 UTC, awqmayo commented on src/items/sumQuestion.jsx
>                  alert("Your sum exceeds the maximum; please change the values inputted.")
I have changed the alert to specify the sum must equal the specified value.

2022-08-02 21:03 UTC, brownsarahm approved these changes

2022-08-02 21:03 UTC, merged